spring:
  application:
    name: valhalla
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/access-control?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: thiago
    password: thiago

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true
